// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeBox.Data;

#nullable disable

namespace RecipeBox.Migrations
{
    [DbContext(typeof(RecipeDbContext))]
    partial class RecipeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("RecipeBox.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CookingTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = "admin",
                            AuthorName = "Admin",
                            Category = "Супи",
                            CookingTime = "1.5 години",
                            CreatedAt = new DateTime(2026, 3, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Ingredients = "Буряк, капуста, картопля, морква, цибуля, томатна паста, м'ясо, сіль, перець, лавровий лист",
                            Instruction = "1. Зварити бульйон. 2. Підсмажити овочі. 3. Додати капусту та картоплю. 4. Варити до готовності. 5. Додати спеції.",
                            Status = "Опубліковано",
                            Title = "Класичний борщ"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = "admin",
                            AuthorName = "Admin",
                            Category = "Основні страви",
                            CookingTime = "1 година",
                            CreatedAt = new DateTime(2026, 3, 21, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Ingredients = "Борошно, вода, сіль, картопля, цибуля, олія, перець",
                            Instruction = "1. Замісити тісто. 2. Приготувати начинку. 3. Зліпити вареники. 4. Відварити в підсоленій воді. 5. Подавати зі сметаною.",
                            Status = "Опубліковано",
                            Title = "Вареники з картоплею"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = "user1",
                            AuthorName = "Олена Петренко",
                            Category = "Салати",
                            CookingTime = "40 хвилин",
                            CreatedAt = new DateTime(2026, 3, 22, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Ingredients = "Куряче філе, салат ромен, пармезан, сухарики, яйце, оливкова олія, гірчиця, лимонний сік",
                            Instruction = "1. Запекти курку. 2. Приготувати соус. 3. Нарізати салат. 4. Змішати всі інгредієнти. 5. Посипати пармезаном.",
                            Status = "На перевірці",
                            Title = "Цезар з куркою"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = "admin",
                            AuthorName = "Admin",
                            Category = "Десерти",
                            CookingTime = "2 години + ніч",
                            CreatedAt = new DateTime(2026, 3, 23, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Ingredients = "Борошно, мед, яйця, цукор, сода, сметана, вершкове масло",
                            Instruction = "1. Замісити тісто. 2. Випекти коржі. 3. Приготувати крем. 4. Зібрати торт. 5. Залишити просочитися на ніч.",
                            Status = "Опубліковано",
                            Title = "Медовик"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = "user2",
                            AuthorName = "Марія Іваненко",
                            Category = "Салати",
                            CookingTime = "15 хвилин",
                            CreatedAt = new DateTime(2026, 3, 24, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Ingredients = "Помідори, огірки, болгарський перець, червона цибуля, фета, маслини, оливкова олія, орегано",
                            Instruction = "1. Нарізати всі овочі. 2. Додати фету та маслини. 3. Заправити оливковою олією. 4. Посипати орегано.",
                            Status = "Відхилено",
                            Title = "Грецький салат"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
